Repository ssisbit/ssis.bit, pull requests merged in 2022-01, with the labels that each got.

#10 menu selection for programs
  hardware/ESP32_S2-Display.pdf
  hardware/README.md
  software/code.py
Labels: documentation

#6 example programs
  basic/README.md
  basic/battery_voltage.py
  basic/bouncy_balls1.py
  basic/button_boot.py
  basic/button_lcdbacklight.py
  basic/clock.py
  basic/helloworld.py
  basic/helloworld_st7789.py
  basic/pin_board.py
  basic/prime10000.py
  basic/wifi_scan.py
  basic/x-test.py
  docs/GPIO.png
  docs/index.md
  docs/io_pins.xlsx
Labels: enhancement

#7 include flashing instructions
  docs/index.md
Labels: documentation

#8 buttons to switch USB OTG
  docs/T8_USB_OTG.png
Labels: bug

#11 standard to revert to for code.py
  software/helloword.py
Labels: enhancement

#16 future i2c connection
  docs/index.md
Labels: documentation, enhancement

#17 bno055 project
  software/rvr/code.py
  software/rvr/lib/adafruit_bno055.mpy
  software/rvr/lib/adafruit_register/__init__.py
  software/rvr/lib/adafruit_register/i2c_bcd_alarm.mpy
  software/rvr/lib/adafruit_register/i2c_bcd_datetime.mpy
  software/rvr/lib/adafruit_register/i2c_bit.mpy
  software/rvr/lib/adafruit_register/i2c_bits.mpy
  software/rvr/lib/adafruit_register/i2c_struct.mpy
  software/rvr/lib/adafruit_register/i2c_struct_array.mpy
Labels: enhancement
